config/routes.rb
Xoxox::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications

  root :to => 'pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :offers do 
  get 'new1', :on => :collection
  get 'new2', :on => :collection
    member do
      get 'edit_thanks'
      get 'thanks'
    end
    resources :subscriptions 
    
  end
  
  match 'users/:id' => 'users#show'
  
  match 'users/create_profile', :to => 'users#create_profile'
  
  match	'users/details',					:to => 'users#details'
  
  match	'offers/new2',					:to => 'offers#new_video'
  match	'offers/new1',					:to => 'offers#new'
  
  match 'user_root' => 'pages#user_page'
  
  match 'user_page' => 'pages#user_page'
  

end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    auth = request.env["rack.auth"]
    current_user.authentications.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
    flash[:notice] = "Authentication successful."
    redirect_to authentications_url
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
  
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<%= semantic_form_for @authentication do |f| %>
  <%= f.inputs do %>
    <%= f.input :user_id %>
    <%= f.input :provider %>
    <%= f.input :uid %>
  <% end %>

  <%= f.buttons do %>
    <%= f.commit_button %>
  <% end %>
<% end %>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>