config/routes.rb
Xoxox::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications

  root :to => 'pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :offers do 
  get 'new1', :on => :collection
  get 'new2', :on => :collection
    member do
      get 'edit_thanks'
      get 'thanks'
    end
    resources :subscriptions 
    
  end
  
  match 'users/:id' => 'users#show'
  
  match 'users/create_profile', :to => 'users#create_profile'
  
  match	'users/details',					:to => 'users#details'
  
  match	'offers/new2',					:to => 'offers#new_video'
  match	'offers/new1',					:to => 'offers#new'
  
  match 'user_root' => 'pages#user_page'
  
  match 'user_page' => 'pages#user_page'
  

end

app/views/pages/home.html.erb
<div class="row">
	<div class="offer_header"> Master Landing Pages With No Prior Experience </div>
</div>

<div class="row">
	<div class="span8">
		<div id="offer_video">
			<iframe src="http://player.vimeo.com/video/31982455?byline=0&amp;portrait=0" width="450" height="300" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe><p><a href="http://vimeo.com/31982455">xoxox.biz</a> from <a href="http://vimeo.com/alexisneely">Alexis Neely</a> on <a href="http://vimeo.com">Vimeo</a>.</p>
		</div>
	</div>
	<div class="span8">
		<div class="row">
	
			<div class="offer_details span7"> 
				<p> Join now to easily and effortlessly start delivering your content online and getting paid without learning how to become an internet marketing master or going through another course you will never implement. </p> 			
				</br></br>
					<div class="row">
						<div class="span2">
							Name: </br></br>
							Email Address: </br> </br>
						</div>
						<div class="span5">
							<input type="text" name="name" id="name"/> </br></br>
							<input type="text" name="email" id="email" />
							</br></br>
							<a class="btn large primary" href="#" id="offer_button">Sign Me Up!</a> 
							
						</div>
					</div>
				
			</div>
			<div class="span1">
			</div>
		</div>
	</div>
</div>
<div class="row" id="offer_bullets">
	<div class="span5 offer_bullet">
		<p>Give away a free taste of your content that entices your prospects to want more</p>
	</div>
	<div class="span5 offer_bullet">
		<p>Then, we'll guide you to "productize" your service, information or knowledge so you can deliver it in modules.</p>
	</div>
	<div class="span5 offer_buller">
		<p>Finally, we'll give you a platform to sell your product online so you can reach a global audience of people who need your Great Work and you can make money while you sleep.</p>
	</div>
</div>
</div>
<script>
	
$("#offer_button").click( function(){
	name = $("#name").val();
	email = $("#email").val();
	current_doc = document.URL;
	
	window.location.replace(document.URL + "users/sign_up/" + "?name=" + name + "&email=" + email )
});

		</script>

app/views/pages/user_page.html.erb
<div class="row">
	<div class="offer_header"> Create Landing Pages </div>
</div>


<%= link_to "Create New Offer With Video", offers_new1_path, :class => "btn large success" %>
<%= link_to "Create New Offer Without Video", offers_new2_path,  :class => "btn large success" %>

</br></br>
</br>
<table>
	<thead>
		<tr> 
			<th> Offer </th>
			<th> Edit Offer Page </th>
			<th> Edit Offer Thanks Page </th>
			<th> Subscribers </th>
			<th> Mailing List </th>
			<th> Delete </th>
		</tr>
	</thead>
	<tbody>
		<% @user.offers.each do |offer| %>
		
		<tr> 
			<th> <%= link_to(offer.name, offer) %> </th>
			<th> <%= link_to 'Edit Show', edit_offer_path(offer) %> </th>
			<th> <%= link_to( 'Edit Thanks', edit_thanks_offer_path(offer) ) %></th>
			<th> <%= offer.subscriptions.count %></th>
			<th> <%=  link_to(  "Subscribers", offer_subscriptions_path(offer) ) %>  </th>
			<th> <%= link_to 'Delete', offer, confirm: 'Are you sure?', method: :delete %>
			 </th>
		</tr>
		<% end %>
	</tbody>
</table>		
			

<br>

</br>