config/routes.rb
Xoxox::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match '/auth/:provider/callback' => 'authentications#create'
  
  resources :authentications

  root :to => 'pages#home'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'sign_in', :to => 'users/sessions#new', :as => :new_user_session
    get 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session
  end

  resources :offers do 
  get 'new1', :on => :collection
  get 'new2', :on => :collection
    member do
      get 'edit_thanks'
      get 'thanks'
    end
    resources :subscriptions 
    
  end
  
  match 'users/:id' => 'users#show'
  
  match 'users/create_profile', :to => 'users#create_profile'
  
  match	'users/details',					:to => 'users#details'
  
  match	'offers/new2',					:to => 'offers#new_video'
  match	'offers/new1',					:to => 'offers#new'
  
  match 'user_root' => 'pages#user_page'
  
  match 'user_page' => 'pages#user_page'
  

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  
  belongs_to :user
  has_many :subscriptions
  
  mount_uploader :attachment, AttachmentUploader
  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # GET /offers
  # GET /offers.json
  def index
    @offers = Offer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offers }
    end
  end

  # GET /offers/1
  # GET /offers/1.json
  def show
    @offer = Offer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @offer }
    end
  end

  # GET /offers/new
  # GET /offers/new.json
  def new1
    @offer = Offer.new
    @user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end

  def new2
    @offer = Offer.new
    @user = current_user
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @offer }
    end
  end 
  
  # GET /offers/1/edit
  def edit
    @offer = Offer.find(params[:id])
  end
  
  # GET /offers/1/edit_thanks
  def edit_thanks
    @offer = Offer.find(params[:id])
  end
  
  def thanks
    @offer = Offer.find(params[:id])
  end
  
  # POST /offers
  # POST /offers.json
  def create
    @offer = Offer.new(params[:offer])
    @offer.user = current_user
    @user = current_user
    respond_to do |format|
      if @offer.save
        format.html { redirect_to edit_thanks_offer_path(@offer), notice: 'Offer was successfully created.' }
        format.json { render json: @offer, status: :created, location: @offer }
      else
        format.html { render action: "new" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offers/1
  # PUT /offers/1.json
  def update
    @offer = Offer.find(params[:id])

    respond_to do |format|
      if @offer.update_attributes(params[:offer])
        format.html { redirect_to user_root_path, notice: 'Offer was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @offer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offers/1
  # DELETE /offers/1.json
  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    respond_to do |format|
      format.html { redirect_to user_root_path }
      format.json { head :ok }
    end
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for @offer, :html => {:multipart => true} do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br />
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :style => "height:100px" %>
  </div>
  <div class="field">
    <%= f.label :bullet1 %><br />
    <%= f.text_field :bullet1 %>
  </div>
  <div class="field">
    <%= f.label :bullet2 %><br />
    <%= f.text_field :bullet2 %>
  </div>
  <div class="field">
    <%= f.label :bullet3 %><br />
    <%= f.text_field :bullet3 %>
  </div>
  <div class="field">
    <%= f.label :button %><br />
    <%= f.text_field :button %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/_form2.html.erb
<%= form_for @offer, :html => {:multipart => true} do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>




<div class="row">
	<div class="offer_header"> <%= f.text_field :name, :class => "offer_header" %> </div>
</div>

<div class="row">
	<div class="span8">
		<div id="offer_video">
			<%= f.text_field :video_url %>
		</div>
	</div>
	<div class="span8">
		<div class="row">
	
			<div class="offer_details span7"> 
				<p> Join now to easily and effortlessly start delivering your content online and getting paid without learning how to become an internet marketing master or going through another course you will never implement. </p> 			
				</br></br>
					<div class="row">
						<div class="span2">
							Name: </br></br>
							Email Address: </br> </br>
						</div>
						<div class="span5">
							<input type="text" name="name" id="name"/> </br></br>
							<input type="text" name="email" id="email" />
							</br></br>
							<a class="btn large primary" href="#" id="offer_button">Sign Me Up!</a> 
							
						</div>
					</div>
				
			</div>
			<div class="span1">
			</div>
		</div>
	</div>
</div>
<div class="row" id="offer_bullets">
	<div class="span5 offer_bullet">
		<p><%= f.text_field :bullet1 %></p>
	</div>
	<div class="span5 offer_bullet">
		<p><%= f.text_field :bullet2 %></p>
	</div>
	<div class="span5 offer_buller">
		<p><%= f.text_field :bullet3 %></p>
	</div>
</div>
</div>

 <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>



<%= render 'form' %>

<%= link_to 'Show', @offer %> |
<%= link_to 'Back', offers_path %>

app/views/offers/edit_thanks.html.erb
<h2> Create a <%= @offer.name %> Thanks Page</h2>
<%= form_for @offer, :html => {:multipart => true} do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :thanks_video %><br />
    <%= f.text_field :thanks_video %>
  </div>
  <div class="field">
    <%= f.label :thanks_audio %><br />
    <%= f.text_field :thanks_audio %>
  </div>
  <div class="field">
    <%= f.label :thanks_text %><br />
    <%= f.text_area :thanks_text %>
  </div>

  <div class="field">
    <%= f.file_field :attachment %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/index.html.erb
<h1>Listing offers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Video url</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @offers.each do |offer| %>
  <tr>
    <td><%= link_to offer.name, offer %></td>
    <td><%= offer.video_url %></td>

    <td>
<% if !offer.user.nil? %>
<%= offer.user.name %></td>
<% end %>
    <td><%= link_to 'Show', offer %></td>
    <td><%= link_to 'Edit', edit_offer_path(offer) %></td>
    <td><%= link_to 'Destroy', offer, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Offer', new_offer_path %>

app/views/offers/new1.html.erb
<%= form_for @offer, :html => {:multipart => true} do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :video_url %><br />
    <%= f.text_field :video_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :style => "height:100px" %>
  </div>
  <div class="field">
    <%= f.label :bullet1 %><br />
    <%= f.text_field :bullet1 %>
  </div>
  <div class="field">
    <%= f.label :bullet2 %><br />
    <%= f.text_field :bullet2 %>
  </div>
  <div class="field">
    <%= f.label :bullet3 %><br />
    <%= f.text_field :bullet3 %>
  </div>
  <div class="field">
    <%= f.label :button %><br />
    <%= f.text_field :button %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/new2.html.erb
<%= form_for @offer, :html => {:multipart => true} do |f| %>
  <% if @offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@offer.errors.count, "error") %> prohibited this offer from being saved:</h2>

      <ul>
      <% @offer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :style => "height:100px" %>
  </div>
  <div class="field">
    <%= f.label :bullet1 %><br />
    <%= f.text_field :bullet1 %>
  </div>
  <div class="field">
    <%= f.label :bullet2 %><br />
    <%= f.text_field :bullet2 %>
  </div>
  <div class="field">
    <%= f.label :bullet3 %><br />
    <%= f.text_field :bullet3 %>
  </div>
  <div class="field">
    <%= f.label :button %><br />
    <%= f.text_field :button %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offers/show.html.erb
<div class="row">
	<div class="offer_header"> <%= @offer.name %>
		 <%= link_to "download", @offer.attachment.url %>
		
   </div>
</div>

<div class="row">
	<div class="span8 offer-bullets-horizontal" >
		<ul>
		<li>
			<%= @offer.bullet1 %>
		</li>
		<li>
			<%= @offer.bullet2 %>
		</li>
		<li>
			<%= @offer.bullet3 %>
		</li>
		</ul>
	</div>
	<div class="span8">
		<div class="row">
	
			<div class="offer_details span7"> 
				<p> <%= @offer.description  %></p> 			
				</br></br>
					<div class="row">
						<div class="span2">
							Name: </br></br>
							Email Address: </br> </br>
						</div>
						
						
				
						<div class="span5">
							<%= form_for [@offer, @offer.subscriptions.build] do |f| %>

							  <%= f.text_field :name %></br></br>

							  <%= f.text_field :email %> </br></br>
							<div class=""><%= f.submit @offer.button , :class => "btn large primary" %></div>
							<% end %>
						</div>
						
					</div>
				
			</div>
			<div class="span1">
			</div>
		</div>
	</div>
</div>
</div>

app/views/offers/thanks.html.erb
</br>
	
	<div class="row">
		<div class="offer_header"> Thank You! </div>
	</div>

	<div class="row">
		<div class="span8 offer_details ">
			<p><%= @offer.thanks_text %></br> </p>
			
		</div>
		<div class="span8">
			<div class="row">

				<div class="offer_details span8"> 
					<div class="span8 offer-bullets-horizontal" >
						<ul>
						<li>
							<%= @offer.bullet1 %>
						</li>
						<li>
							<%= @offer.bullet2 %>
						</li>
						<li>
							<%= @offer.bullet3 %>
						</li>
						</ul>
					</div>

				</div>

			</div>
		</div>
	</div>
	</div>